version: "3.7"
services:
  ####################### SEARCH API ###########################################
  search-api:
    build:
      context: app
      args:
        PROJECT_NAME: SearchAPI
    environment:
      RABBITMQ__HOST: rabbitmq
      RABBITMQ__PORT: 5672
      RABBITMQ__USERNAME: guest
      RABBITMQ__PASSWORD: guest
    ports:
      - "8081:80"
    restart: always
    networks:
      - fams-integration
    depends_on:
      - rabbitmq
      - postgres

  ####################### SEARCH TRACKER #######################################
  search-api-tracker:
    build:
      context: app
      args:
        PROJECT_NAME: SearchApi.Tracker
    environment:
      RABBITMQ__HOST: rabbitmq
      RABBITMQ__PORT: 5672
      RABBITMQ__USERNAME: guest
      RABBITMQ__PASSWORD: guest
      CONNECTIONSTRINGS__STATEMACHINECONTEXT: Host=postgres;Database=state_machine;Username=admin;Password=admin
    restart: always
    networks:
      - fams-integration
    depends_on:
      - rabbitmq
      - postgres

  ####################### DB MIGRATION #######################################
  state-machine-migration:
    build:
      context: app
      target: build
      args:
        PROJECT_NAME: SearchApi.Tracker
    environment:
      CONNECTIONSTRINGS__STATEMACHINECONTEXT: Host=postgres;Database=state_machine;Username=admin;Password=admin
      WAIT_HOSTS: postgres:5432
    command: sh -c "/wait && dotnet ef database update"
    networks:
      - fams-integration
    depends_on:
      - rabbitmq
      - postgres

  ####################### RABBITMQ SERVER ######################################
  rabbitmq:
    image: rabbitmq:3.7.15-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - data-rabbit:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    restart: always
    networks:
      - fams-integration

  ####################### POSTGRES SERVER ######################################
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: state_machine
    networks:
      - fams-integration

  ####################### POSTGRES ADMIN ######################################
  omnidb:
    image: taivokasper/omnidb
    restart: always
    ports:
      - 8091:8080
      - 25482:25482
    networks:
      - fams-integration
    depends_on:
      - postgres    

  ####################### JOB MANAGER API ###########################################
  jobmanager:
    build:
      context: app
      args:
        PROJECT_NAME: JobManager
    restart: always
    networks:
      - fams-integration
    depends_on:
      - search-api


networks:
  fams-integration:
    driver: bridge

volumes:
  data-rabbit:
  data-redis:
